#include "stdafx.h"

using namespace std;

namespace Puzzle03_2017_Types
{
	class spiral_iterator
	{
	public:
		using value_type = pair<int32_t, Vec2Int>;
		using difference_type = ptrdiff_t;

		spiral_iterator()
		{
		}

		explicit spiral_iterator(const Vec2Int& start)
			: Current({ 1, start })
		{
		}

		spiral_iterator(const spiral_iterator&) = default;

		const value_type& operator*() const
		{
			return Current;
		}

		const value_type* operator->() const
		{
			return &Current;
		}

		spiral_iterator& operator++()
		{
			Next();
			return *this;
		}

		spiral_iterator operator++(int)
		{
			spiral_iterator prev{ *this };
			Next();
			return prev;
		}

		inline bool operator==(const spiral_iterator& other) const
		{
			// Minimum support for comparing against end sentinel
			return Current == other.Current;
		}

	private:

		void Next()
		{
			// Move current point
			Current.first++;
			Current.second = Current.second + DirectionCycle[SpiralArmIndex % 4];

			// Turn corner to new arm if needed
			SpiralArmCount++;
			if (SpiralArmCount == SpiralArmLength)
			{
				SpiralArmIndex++;
				SpiralArmLength = (SpiralArmIndex / 2) + 1;
				SpiralArmCount = 0;
			}
		}

		// The square spiral is generated by moving:
		// Rx1 Ux1 Lx2 Dx2 Rx3 Ux3 Lx4 Dx4 ...
		// Cycling Right, Up, Left, Down at each turn
		// Moving with lengths before turns that increase in pairs:
		// 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, ...

		int32_t SpiralArmIndex = 0; // Where we are in the RULD cycle
		int32_t SpiralArmLength = 1; // The length of the currently active 'arm'
		int32_t SpiralArmCount = 0; // How far through the arm we are before the turn comes up

		value_type Current{ -1, { numeric_limits<int32_t>::max(), numeric_limits<int32_t>::max() } };

		vector<Vec2Int> DirectionCycle = vector<Vec2Int>{ Vec2Int::Right(), Vec2Int::Up(), Vec2Int::Left(), Vec2Int::Down() };
	};

	inline bool operator!=(const spiral_iterator& a, const spiral_iterator& b)
	{
		return !(a == b);
	}

	static_assert(input_or_output_iterator<spiral_iterator>);

	class spiral_view : public ranges::view_interface<spiral_view>
	{
	public:
		spiral_iterator begin() const
		{
			return spiral_iterator{ Vec2Int{ 0, 0 } };
		}

		spiral_iterator end() const
		{
			return {};
		}
	};

	spiral_view spiral()
	{
		return {};
	}
}

using namespace Puzzle03_2017_Types;

static Vec2Int SquareSpiralCoordinates(int32_t n)
{
	if (n == 1)
	{
		return { 0, 0 };
	}

	int32_t offsetN = n - 1;

	int32_t ringIndex = (static_cast<int32_t>(sqrt(offsetN)) + 1) / 2;
	int32_t ringBegin = ((ringIndex * 2) - 1) * ((ringIndex * 2) - 1);
	int32_t ringEnd = (((ringIndex + 1) * 2) - 1) * (((ringIndex + 1) * 2) - 1);
	int32_t ringOffset = offsetN - ringBegin;
	int32_t ringSize = ringEnd - ringBegin;

	int32_t ringQuadrant = (ringOffset * 4) / ringSize;

	int32_t quadrantSize = ringSize / 4;
	int32_t quadrantBegin = ringBegin + (ringQuadrant * quadrantSize);
	int32_t quadrantOffset = offsetN - quadrantBegin;

	switch (ringQuadrant)
	{
	case 0: return { ringIndex, ringIndex - 1 - quadrantOffset };
	case 1: return { ringIndex - 1 - quadrantOffset, -ringIndex };
	case 2: return { -ringIndex, -ringIndex + 1 + quadrantOffset };
	case 3: return { -ringIndex + 1 + quadrantOffset, ringIndex };
	}

	return { 0, 0 };
}

void Puzzle03_A_2017()
{
	int32_t spiralIndex = Parse::GetInt32();
	Vec2Int spiralCoordinate = SquareSpiralCoordinates(spiralIndex);

	int32_t answer = abs(spiralCoordinate.X) + abs(spiralCoordinate.Y);

	PuzzleOutput::Submit(2017, 3, 1, answer);
}

void Puzzle03_B_2017()
{
	int32_t targetValue = Parse::GetInt32();

	int32_t answer = 0;

	const size_t hashTableSize = 256;
	HashMap<Vec2Int, int32_t> spiralValues(hashTableSize, { numeric_limits<int32_t>::min(), numeric_limits<int32_t>::min() });
	for (const auto& p : spiral())
	{
		int32_t surroundingSum = 0;
		for (const auto& dir : Vec2Int::CardinalAndDiagonalDirections())
		{
			surroundingSum += spiralValues.FindOrDefault(p.second + dir, 0);
		}

		int32_t spiralValue = max<int32_t>(surroundingSum, 1);
		spiralValues.Insert(p.second, spiralValue);

		if (spiralValue > targetValue)
		{
			answer = spiralValue;
			break;
		}
	}

	PuzzleOutput::Submit(2017, 3, 2, answer);
}
