get_filename_component(LIB_NAME ${CMAKE_CURRENT_SOURCE_DIR} NAME)
file(GLOB SOURCE_FILES *.cpp)
add_library(${LIB_NAME} ${SOURCE_FILES})
target_include_directories(${LIB_NAME} PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(${LIB_NAME} PUBLIC win32_settings)
target_link_libraries(${LIB_NAME} PUBLIC pico_platform_headers)
target_link_libraries(${LIB_NAME} PUBLIC pico_settings)
target_link_libraries(${LIB_NAME} PRIVATE MicroUtilities)
if(PICO_BOARD)
    pico_enable_stdio_uart(${LIB_NAME} 0)
    pico_enable_stdio_usb(${LIB_NAME} 1)
    target_link_libraries(${LIB_NAME} PRIVATE pico_stdlib)
endif()